install: gradle wrapper --gradle-version 5.4.1
language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28

before_script:
  - chmod +x gradlew

script:
  - chmod +x ./gradlew
  - ./gradlew assembleDebug
  - ./gradlew test